"""
Mock Order Management System (OMS) database.

In production this would be a read-only DB replica or a dedicated read API.
The agent ONLY queries this — it never writes to it directly.
All writes (refunds, returns) go through the executor node AFTER human approval.
"""

MOCK_ORDERS: dict[str, dict] = {
    "ORD-78234": {
        "order_id": "ORD-78234",
        "customer_id": "CUST-4821",
        "item_name": "Samsung 55-inch 4K Smart TV",
        "item_value": 52000.0,
        "payment_method": "Credit Card",
        "order_date": "2025-01-07",
        "delivery_date": "2025-01-10",
        "order_status": "Delivered",
        "return_window_days": 10,
        "days_since_delivery": 5,
        "return_eligible": True,
        "previous_refund_processed": False,
        "carrier_confirmation": "UNDELIVERED — carrier marked delivered but no signature captured",
    },
    "ORD-65891": {
        "order_id": "ORD-65891",
        "customer_id": "CUST-3317",
        "item_name": "Nike Air Max 270 Running Shoes",
        "item_value": 8500.0,
        "payment_method": "UPI",
        "order_date": "2024-12-10",
        "delivery_date": "2024-12-13",
        "order_status": "Delivered",
        "return_window_days": 30,
        "days_since_delivery": 33,
        "return_eligible": False,
        "previous_refund_processed": False,
        "carrier_confirmation": None,
    },
    "ORD-91023": {
        "order_id": "ORD-91023",
        "customer_id": "CUST-9104",
        "item_name": "Dell XPS 15 Laptop",
        "item_value": 89000.0,
        "payment_method": "Credit Card",
        "order_date": "2025-01-12",
        "delivery_date": "2025-01-14",
        "order_status": "Delivered",
        "return_window_days": 10,
        "days_since_delivery": 1,
        "return_eligible": True,
        "previous_refund_processed": False,
        "carrier_confirmation": "Delivered — package condition not documented",
    },
    "ORD-44567": {
        "order_id": "ORD-44567",
        "customer_id": "CUST-2256",
        "item_name": "Roadster Blue Shirt Size L",
        "item_value": 1200.0,
        "payment_method": "Debit Card",
        "order_date": "2025-01-13",
        "delivery_date": "2025-01-14",
        "order_status": "Delivered",
        "return_window_days": 30,
        "days_since_delivery": 1,
        "return_eligible": True,
        "previous_refund_processed": False,
        "carrier_confirmation": None,
    },
    "ORD-55120": {
        "order_id": "ORD-55120",
        "customer_id": "CUST-7733",
        "item_name": "OnePlus 12 5G Smartphone",
        "item_value": 45000.0,
        "payment_method": "Credit Card",
        "order_date": "2025-01-01",
        "delivery_date": "2025-01-03",
        "order_status": "Return Received at Warehouse",
        "return_window_days": 10,
        "days_since_delivery": 12,
        "return_eligible": False,
        "previous_refund_processed": False,
        "carrier_confirmation": "Return pickup confirmed on 2025-01-05. Received at warehouse 2025-01-06.",
    },
}
